name: build-authorization-service
on:
  push:
    branches:
      - master
jobs:
  build:
    name: build-service
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.12
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Install  dependencies
        run: go mod download
        working-directory: ./

      - name: Build
        run: go build -v .
        working-directory: ./
