name: build-authorization-service
on:
  push:
    branches:
      - master
jobs:
  build:
    name: build-service
    runs-on: ubuntu-latest
    steps:
      - continue-on-error: false
      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.12
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Install  dependencies
        run: go mod download
        working-directory: ./

      - name: Build
        run: go build -v .
        working-directory: ./

      - name: Upload build
        uses: actions/upload-artifact@v1
        with:
          name: build
          path: authorization-service
  test:
    name: test-service
    runs-on: ubuntu-latest
    needs: build
    steps:
      - continue-on-error: false
      - name: Download build
        uses: actions/download-artifact@v1
        with:
          name: build

      - name: test-user-service
        run: go test ./test/...
        working-directory: ./
